samples:
  8714-MV-2_AAGGAGCG-CAATAGTC:
    fastqs: /nfs/turbo/umms-parent/Carmen/8714-MV/fastqs_8714-MV
    transcriptome: /nfs/turbo/umms-parent/Manny_human_ref/refdata-gex-GRCh38-2020-A

output_dir: /nfs/turbo/umms-parent/Manny_test