project_name: "Bioinformatics Workflow Engine"
experimenter: "Your Name"
date: "YYYY-MM-DD"  # Update with the current date

# Project paths
project_path: "/nfs/turbo/umms-parent/test_project_bioinfo_workflow"  # Update with the actual project path
data_dir: "data"
results_dir: "results"
logs_dir: "logs"

# Workflow parameters
workflows:
  - name: "CellRangerWorkflow"
    enabled: true
    parameters:
      param1: "value1"
      param2: "value2"

  - name: "VentralWorkflow"
    enabled: true
    parameters:
      param1: "value1"
      param2: "value2"

  - name: "QCWorkflow"
    enabled: true
    parameters:
      param1: "value1"
      param2: "value2"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Additional parameters can be added as needed
