# This file was auto-generated by create_workflow_scaffold.py
# Class: MyNewWorkflow
# File: my_new_workflow.py (snake_case match required for registration)

from .base_workflow import BaseWorkflow

class MyNewWorkflow(BaseWorkflow):
    """
    MyNewWorkflow class that inherits from BaseWorkflow.
    Implements specific logic for the MyNewWorkflow pipeline.
    """

    def __init__(self, config):
        super().__init__(config)
        self.workflow_name = "MyNewWorkflow"
        self.setup_paths()

    def run(self):
        """
        Execute the MyNewWorkflow workflow.
        """
        if not self.config.get("force_rerun", False) and self.is_already_completed():
            print(f"✅ Skipping {self.workflow_name}; already completed.")
            return

        self.log_start()

        # TODO: Add your workflow steps here
        # Example: self.step_one()
        #
        # No need to call self.mark_completed() — handled automatically by the base class logic.

        self.log_end()
